spring:
  datasource:
      url: jdbc:mysql://192.168.1.10:3306/vivashowcenter?useUnicode=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: xiaoyingtv
      password: quvideo2012
server:
  port: 8002